from mininet.net import Mininet
from mininet.cli import CLI
net = Mininet()
s1 = net.addSwitch('s1')
c1 = net.addController('c1')
s2 = net.addSwitch('s2')
s3 = net.addSwitch('s3')
s4 = net.addSwitch('s4')
h1 = net.addHost('h1')
h2 = net.addHost('h2')
net.addLink(h1,s2)
net.addLink(s2,s4)
net.addLink(s4,h2)
net.addLink(s2,s1)
net.addLink(s1,s3)
net.addLink(s3,s4)
net.start()
CLI(net)
